#############################################################################
# Makefile for building: untitled.app/Contents/MacOS/untitled
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  untitled.pro
# Template: app
# Command: /Volumes/Brick/Qt/5.8/clang_64/bin/qmake -o Makefile untitled.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Volumes/Brick/Qt/5.8/clang_64/mkspecs/macx-clang -F/Volumes/Brick/Qt/5.8/clang_64/lib
QMAKE         = /Volumes/Brick/Qt/5.8/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = untitled1.0.0
DISTDIR = /Users/btendrich/untitled/.tmp/untitled1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_LFLAGS) -Wl,-rpath,/Volumes/Brick/Qt/5.8/clang_64/lib
LIBS          = $(SUBLIBS) -F/Volumes/Brick/Qt/5.8/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtNetwork -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		timercontroller.cpp \
		overheadcontroller.cpp moc_mainwindow.cpp \
		moc_timercontroller.cpp \
		moc_overheadcontroller.cpp
OBJECTS       = main.o \
		mainwindow.o \
		timercontroller.o \
		overheadcontroller.o \
		moc_mainwindow.o \
		moc_timercontroller.o \
		moc_overheadcontroller.o
DIST          = /Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/uic.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		untitled.pro mainwindow.h \
		timercontroller.h \
		overheadcontroller.h main.cpp \
		mainwindow.cpp \
		timercontroller.cpp \
		overheadcontroller.cpp
QMAKE_TARGET  = untitled
DESTDIR       = 
TARGET        = untitled.app/Contents/MacOS/untitled


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d untitled.app/Contents/MacOS/ || mkdir -p untitled.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: untitled.pro /Volumes/Brick/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf /Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/uic.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		untitled.pro \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile untitled.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qml_debug
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/qdevice.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/device_config.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/unix.conf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/mac.conf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/macx.conf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/clang.conf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/qconfig.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/default_post.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qml_debug.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qt.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/resources.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/moc.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/uic.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/yacc.prf:
/Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/lex.prf:
untitled.pro:
/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile untitled.pro -spec macx-clang CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

untitled.app/Contents/PkgInfo: 
	@test -d untitled.app/Contents || mkdir -p untitled.app/Contents
	@$(DEL_FILE) untitled.app/Contents/PkgInfo
	@echo "APPL????" > untitled.app/Contents/PkgInfo
untitled.app/Contents/Resources/empty.lproj: 
	@test -d untitled.app/Contents/Resources || mkdir -p untitled.app/Contents/Resources
	@touch untitled.app/Contents/Resources/empty.lproj
	
untitled.app/Contents/Info.plist: 
	@test -d untitled.app/Contents || mkdir -p untitled.app/Contents
	@$(DEL_FILE) untitled.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,Blank.untitled,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,untitled,g" -e "s,@LIBRARY@,untitled,g" -e "s,@TYPEINFO@,????,g" /Volumes/Brick/Qt/5.8/clang_64/mkspecs/macx-clang/Info.plist.app >untitled.app/Contents/Info.plist

all: Makefile \
		untitled.app/Contents/PkgInfo \
		untitled.app/Contents/Resources/empty.lproj \
		untitled.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h timercontroller.h overheadcontroller.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp timercontroller.cpp overheadcontroller.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r untitled.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.9 $(EXPORT_QMAKE_XARCH_CFLAGS) -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /Volumes/Brick/Qt/5.8/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_timercontroller.cpp moc_overheadcontroller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_timercontroller.cpp moc_overheadcontroller.cpp
moc_mainwindow.cpp: /Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QNetworkInterface \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QSettings \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		timercontroller.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QTcpSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QAbstractSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		overheadcontroller.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QUrl \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qurl.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		mainwindow.h \
		moc_predefs.h \
		/Volumes/Brick/Qt/5.8/clang_64/bin/moc
	/Volumes/Brick/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Volumes/Brick/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/btendrich/untitled -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Volumes/Brick/Qt/5.8/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_timercontroller.cpp: /Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QTcpSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QAbstractSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		timercontroller.h \
		moc_predefs.h \
		/Volumes/Brick/Qt/5.8/clang_64/bin/moc
	/Volumes/Brick/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Volumes/Brick/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/btendrich/untitled -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Volumes/Brick/Qt/5.8/clang_64/lib timercontroller.h -o moc_timercontroller.cpp

moc_overheadcontroller.cpp: /Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QUrl \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qurl.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		overheadcontroller.h \
		moc_predefs.h \
		/Volumes/Brick/Qt/5.8/clang_64/bin/moc
	/Volumes/Brick/Qt/5.8/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Volumes/Brick/Qt/5.8/clang_64/mkspecs/macx-clang -I/Users/btendrich/untitled -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers -I/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Volumes/Brick/Qt/5.8/clang_64/lib overheadcontroller.h -o moc_overheadcontroller.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/Volumes/Brick/Qt/5.8/clang_64/bin/uic
	/Volumes/Brick/Qt/5.8/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QNetworkInterface \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QSettings \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		timercontroller.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QTcpSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QAbstractSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		overheadcontroller.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QUrl \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qurl.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QNetworkInterface \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDir \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdir.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QSettings \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		timercontroller.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QTcpSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QAbstractSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		overheadcontroller.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QUrl \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qurl.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

timercontroller.o: timercontroller.cpp timercontroller.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QTcpSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QAbstractSocket \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QDebug \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timercontroller.o timercontroller.cpp

overheadcontroller.o: overheadcontroller.cpp overheadcontroller.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QObject \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QUrl \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qurl.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QTimer \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/QXmlStreamReader \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/QImage \
		/Volumes/Brick/Qt/5.8/clang_64/lib/QtGui.framework/Headers/qimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o overheadcontroller.o overheadcontroller.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_timercontroller.o: moc_timercontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_timercontroller.o moc_timercontroller.cpp

moc_overheadcontroller.o: moc_overheadcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_overheadcontroller.o moc_overheadcontroller.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

